Algoritmo "Verificar senha"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 25/09/2024
Var
senha: inteiro


Inicio
escreva("Digite a senha: ")
leia(senha)

se (senha= 1234) entao
escreval("ACESSO PERMITIDO")
senao
escreval("ACESSO NEGADO")
fimse

Fimalgoritmo